### ISSUE TITLE
Build fails

### ISSUE THREAD

**Issue by vadimtk** [fbertram/TuringTrader#1]
I am trying to build
"Build BooksAndPubs project (will link against the binary version installed)"

And I have the following issues:
  Restore completed in 128.29 ms for C:\Users\TuringTrader\BooksAndPubs\BooksAndPubs.csproj.
C:\Program Files\dotnet\sdk\3.1.201\Microsoft.Common.CurrentVersion.targets(2081,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "TuringTrader.Simulator". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [C:\Users\TuringTrader\BooksAndPubs\BooksAndPubs.csproj]
Aeromir_ParkingTrade.cs(56,20): error CS0234: The type or namespace name 'Indicators' does not exist in the namespace 'TuringTrader' (are you missing an assembly reference?) [C:\Users\TuringTrader\BooksAndPubs\BooksAndPubs.csproj]
Aeromir_ParkingTrade.cs(57,20): error CS0234: The type or namespace name 'Simulator' does not exist in the namespace 'TuringTrader' (are you missing an assembly reference?) [C:\Users\TuringTrader\BooksAndPubs\BooksAndPubs.csproj]
Alvarez_EtfSectorRotation.cs(29,20): error CS0234: The type or namespace name 'Indicators' does not exist in the namespace 'TuringTrader' (are you missing an assembly reference?) [C:\Users\TuringTrader\BooksAndPubs\BooksAndPubs.csproj]
Alvarez_EtfSectorRotation.cs(30,20): error CS0234: The type or namespace name 'Simulator' does not exist in the namespace 'TuringTrader' (are you missing an assembly reference?) [C:\Users\TuringTrader\BooksAndPubs\BooksAndPubs.csproj]

**Comment by fbertram** [comment]
Do you have a **binary** version of TuringTrader installed? For purposes of the binary distribution, the BooksAndPubs project links against the binary in c:/Program Files/...

If you are not planning to create a new binary, I recommend the following
* remove the reference to the simulator **binary** from the BooksAndPubs project
* add a reference to the TuringTrader.Simulator **project** instead
