### ISSUE TITLE
Modifying showcase algorithms

### ISSUE THREAD

**Issue by matcha21** [fbertram/TuringTrader#10]
Hi, I copied the Bensdorp file script in the Documents\TuringTrader\BooksAndPubs folder, and pasted it in the \Algorithms folder, to be able to modify it. Unfortunately, I get the error message below (I cut it short since it lists pretty much . What am I doing wrong?

Also, it seems that some scripts, such as LI_UniversalInvestment, are showing in the Turing Trader dropdown menu, but are not in the \BooksAndPubs folder. Are the showcase alogirthms hardcoded into the software?

I also notice some references in the \BooksAndPubs algos, like "Globals", that I could not find a reference to in the TuringTrader.org documentation. Can you provide some explanation on this?

Line 34: CS0234 - The type or namespace name 'Algorithms' does not exist in the namespace 'TuringTrader' (are you missing an assembly reference?)
Line 543: CS0246 - The type or namespace name 'LazyPortfolio' could not be found (are you missing a using directive or an assembly reference?)
Line 559: CS0246 - The type or namespace name 'LazyPortfolio' could not be found (are you missing a using directive or an assembly reference?)
Line 43: CS0246 - The type or namespace name 'AlgorithmPlusGlue' could not be found (are you missing a using directive or an assembly reference?)
Line 561: CS0115 - 'Bensdorp_30MinStockTrader_MRL_MRS_Combo.Name': no suitable method found to override
Line 563: CS0115 - 'Bensdorp_30MinStockTrader_MRL_MRS_Combo.ALLOCATION': no suitable method found to override
Line 568: CS0115 - 'Bensdorp_30MinStockTrader_MRL_MRS_Combo.BENCH': no suitable method found to override
...
Line 59: CS0103 - The name 'Assets' does not exist in the current context
Line 48: CS0103 - The name 'Universes' does not exist in the current context
Line 554: CS0103 - The name 'Globals' does not exist in the current context
...

**Comment by fbertram** [comment]
This is not a bug - you're doing it wrong.

TuringTrader supports two ways of executing code:

(1) run directly from C# source code. This is how the demo algorithms are implemented and is only suitable for the simplest of algorithms. For this to work, all code for the algorithm needs to reside in a single file and you will not be able to add additional references.

(2) run from a DLL. This is how the showcase algorithms are implemented. Doing so, you are free to do everything you can imagine with C#... but you will need to install MSVC and compile the library prior to running any code in it.

If you want to modify the showcase algorithms, please open the project in <your user folder>/Documents/TuringTrader/BooksAndPubs/BooksAndPubs.sln

I need to write an article for the quick start guide here...

Hope this helps,
Best regards, Felix
