### ISSUE TITLE
The name 'TradeStation' does not exist in the current context

### ISSUE THREAD

**Issue by Neconspictor** [fbertram/TuringTrader#16]
When trying to compile the BooksAndPubsV2 project I get the above error message in the file Ehlers_TechnicalPapers.cs.

**Comment by fbertram** [comment]
David, Thanks for reporting. This issue is fixed on the development branch. I will compile a new binary release asap.

In the meantime, add the following definitions around line 232:
    double Cosine(double a) => Math.Cos(Math.PI / 180.0 * a);
    double Sine(double a) => Math.Sin(Math.PI / 180.0 * a);

Next, make the following edits:
    TradeStation.Cosine => Cosine
    TraseStation.Sine => Sine

Best regards, Felix
