### ISSUE TITLE
How do you close an option position before expiry?

### ISSUE THREAD

**Issue by fperugini** [fbertram/TuringTrader#22]
I cannot seem to close out an option position? The behavior seems strange. For example if I open a LEAP call position 2 years out:

```
_incomePosition.Trade(_incomecurrentlots, OrderType.openNextBar)
        .Comment = "LEAP income position open";
```

Then try to close it 1 year before expiration:
```
_incomePosition.Trade(_incomecurrentlots, OrderType.closeThisBar)
         .Comment = "income position close";
```

It does not appear to close the position.

01/11/2010, Enhanced Buy and Hold: Buy 908x SPY
01/11/2010, Enhanced Buy and Hold: Buy 9x SPY121221C00090000    <------- this is the first LEAP call open
01/10/2011, Enhanced Buy and Hold: Buy 9x SPY121221C00090000    <------- This is the attempted close 1 year before expiration
01/10/2011, Enhanced Buy and Hold: Buy 47x SPY
01/10/2011, Enhanced Buy and Hold: Buy 9x SPY131220C00100000
01/09/2012, Enhanced Buy and Hold: Buy 9x SPY131220C00100000
.
.
.
12/31/2019, Enhanced Buy and Hold: Sell -1445x SPY <---- The only time I actually see a sell on the option contracts is at the end of the simulation when all positions get closed out.

btw, this is with the v1 simulator.

Any advise here Felix?

Thanks,
-Frank

**Comment by fbertram** [comment]
Please check the documentation here:
https://www.turingtrader.org/help/api/TuringTrader.Simulator.Instrument.html#TuringTrader_Simulator_Instrument_Trade_System_Int32_TuringTrader_Simulator_OrderType_System_Double_System_Func_TuringTrader_Simulator_Instrument_System_Boolean__

The **first parameter specifies the quantity**. Use positive values to buy, and negative values to sell shares.

The **second parameter specifies the timing** of the order fill. OrderType.openNextBar will execute the trade on the next bar's open, while OrderType.closeThisBar will execute the trade on this bar's close. Your options quotes most likely do not contain opening prices, but snapshots of bid and ask prices taken near the close of the day (typically at 3:45pm). Consequently, any sims using openNextBar will be inaccurate.

**Comment by fperugini** [comment]
The negative values to sell was the key, Thank you.

And you're correct, my option quotes do not contain opening prices, so openNextBar will be inaccurate but fortunately I'm testing long dated options that don't vary that much over that 1 day period.
