### ISSUE TITLE
New DataSource

### ISSUE THREAD

**Issue by akitelesforo** [fbertram/TuringTrader#3]
Good day!

I want to try your application with my data.
https://www.turingtrader.org/help/articles/CreateDataSources.html - The documentation seems incomplete.
Lets say I got the List<> of my data with symbol, open, high, low, close, volume. is there a pattern that I can follow?

Thank you

**Comment by fbertram** [comment]
Hi Akito,
thanks for reaching out. I have added a working demo here: https://www.turingtrader.org/help/articles/CreateDataSources.html

Hope this helps,
best regards, Felix
