### ISSUE TITLE
Issues with Datasource tiingo

### ISSUE THREAD

**Issue by moieric11** [fbertram/TuringTrader#7]
Hi all!

When I get the stock data from tiingo, if I change later the date of the global variable "END_TIME" to get the last data of the current week, it doesn't download the new data, so the stock is noted as "delisted". How to tell turingtrader to update correctly the data, I have to delete the data from the cache everyweek to update the full data.

**Comment by fbertram** [comment]
Let me look into this. Please notice that END_TIME is defined in a possibly surprising way:
```
public static readonly DateTime END_TIME = DateTime.Now.Date - TimeSpan.FromDays(5);
```

**Comment by fbertram** [comment]
I fixed an issue w/ the cache timestamps. Find the commit here:
https://github.com/fbertram/TuringTrader/commit/ac13a48926b2ccf171130810c01e41a9bd982d1a

I also compiled a new binary version. Please note that this is compiled from the development branch:
https://www.turingtrader.org/downloads/TuringTrader_Setup_v0.14.2.msi

Let me know if you see any issues with this.

**Comment by moieric11** [comment]
thank you, it works well

**Comment by fbertram** [comment]
thanks for letting me know.
