### ISSUE TITLE
Missing Invariant culture in CSV Double parser

### ISSUE THREAD

**Issue by gluwer** [fbertram/TuringTrader#8]
Hi,

Thank you for the great software you made available. It is real help in quick testing some tactical trading ideas.

I've found a bug in the CSV that you may not be aware of because you have in system "." as decimal separator, but in Poland where I live it is ",", so `Double` parser throws an error and all read values end up beeing zeros.

The bug is in line https://github.com/fbertram/TuringTrader/blob/7a32cb82528efe2f643565224d3eed3d3ed5c822/TuringTrader.Simulator/DataSources/DataSourceCsv.cs#L64 and simple adding Invariant configuration helps.

Regards,
Rafal

**Comment by fbertram** [comment]
Hello Rafal,
thank you so much for reporting this issue, your help is greatly appreciated. You are correct, these types of errors are hard to find as I live in the US and test the code in that locality. I fixed the issue and committed it to the development branch. Let me know if you need anything else.
Thanks again,
Best regards

Felix
